### ISSUE TITLE
notes skipped

### ISSUE THREAD

**Issue by cyayon** [MatejLach/1password-linux-to-bitwarden#1]
Hello,

it seems that notes in items are not exported and just skipped.
i am using 1password8 for MacOS (early-access).

thanks.

**Comment by MatejLach** [comment]
Hey cyayon , 

Notes are indeed skipped at the moment as I did not personally use them. 
However it is something that I'd look into shortly now that I know there's interest, thanks for letting me know.

**Comment by cyayon** [comment]
thanks.

**Comment by MatejLach** [comment]
@cyayon Finally got around to implementing this. I've also published a binary release so you no longer have to compile it yourself:

https://github.com/MatejLach/1password-linux-to-bitwarden/releases/tag/1.0

**Comment by cyayon** [comment]
Hi,

Thank you very much !



-- 
  Christophe Yayon
