### ISSUE TITLE
Cannot change file location in binary

### ISSUE THREAD

**Issue by guslanzetta1** [MatejLach/1password-linux-to-bitwarden#3]
Hi, tried the binary for Windows and the Linux one and both can't open the file because they search an non-existent location. 

invalid file path; pass '--1pass-backup-file-path=/absolute/path/to/file.1pux'

**Comment by MatejLach** [comment]
Hey, could you paste the entire command + arguments you ran when you got that error?

**Comment by MatejLach** [comment]
Closing due to a lack of response. Please reopen if this is still an issue.
